# Generated by Django 4.2.3 on 2023-07-07 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nintendo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Versao',
            new_name='Modelo',
        ),
    ]
