# Generated by Django 4.2.3 on 2023-07-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=200)),
                ('data_lanc', models.DateField()),
                ('foto', models.ImageField(upload_to='imagens/%Y/%m/%d/')),
                ('link', models.CharField(max_length=50)),
            ],
        ),
    ]
